name: Build and deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - run: ./gradlew shadowJar --no-daemon
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
